/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-05-26 04:40:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.example.database.*;

public final class insert_005fproducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("    <title>Orders - IF532 JSP</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"css/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody { font-size: 140%; }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  \t");

  		if(request.getParameter("insert")!=null)
  		{
  			out.println("asd");
  			if(NorthwindDB.insertProducts(request.getParameter("txtName"), request.getParameter("txtQty"),Integer.parseInt(request.getParameter("txtPrice")) , Integer.parseInt(request.getParameter("txtStock"))))
  				out.println("insert berhasil");
  		}
  	
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t  </button>\r\n");
      out.write("\t\t\t  <a class=\"navbar-brand\" href=\"#\">[IF532] Object Oriented Programming 2</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Products</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#\">Orders<span class=\"sr-only\">(current)</span></a></li>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t\t</div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t</div><!-- /.container-fluid -->\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('#example').dataTable();\r\n");
      out.write("\t\t} );\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t <form method=\"POST\" action = \"#\">\r\n");
      out.write("\t\t \t<table>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\tProduct Name :\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" name=\"txtName\">\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t</tr>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\tQuantity Per Unit : \r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" name=\"txtQty\">\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t</tr>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\tPrice :\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" name=\"txtPrice\">\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t</tr>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\tStock :\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t\t<td>\r\n");
      out.write("\t\t \t\t\t<input type=\"text\" name=\"txtStock\">\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t</tr>\r\n");
      out.write("\t\t \t<tr>\r\n");
      out.write("\t\t \t\t<td colspan=\"4\">\r\n");
      out.write("\t\t \t\t\t<input type=\"submit\" value=\"Insert Data\" name=\"insert\">\r\n");
      out.write("\t\t \t\t</td>\r\n");
      out.write("\t\t \t</tr>\r\n");
      out.write("\t\t\t<!-- Product Name : <input type=\"text\" name=\"txtName\"><br>\r\n");
      out.write("\t\t\tQuantity Per Unit : <input type=\"text\" name=\"txtQty\"><br>\r\n");
      out.write("\t\t\tPrice : <input type=\"text\" name=\"txtPrice\"><br>\r\n");
      out.write("\t\t\tStock : <input type=\"text\" name=\"txtStock\"><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Insert Data\">\r\n");
      out.write("\t\t\t -->\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
